### ISSUE TITLE
100-Days-Of-ML-Code中文版 链接失效

### ISSUE THREAD

**Issue by fighterhit** [sjsdfg/CS-Notes-PDF#3]
100-Days-Of-ML-Code中文版 链接失效

**Comment by sjsdfg** [comment]
已经找到新的github了。
估计是那个作者发现别人的工作更好，去contribute别人的项目去了
看了看那个人的commit记录 。。。。

**Comment by sjsdfg** [comment]
https://github.com/Avik-Jain/100-Days-of-ML-Code-Chinese-Version
